sudo: required
services:
  - docker

before_install:
  - docker build -t ranggarmaste/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ranggarmaste/docker-react npm run test

docker:
  provider: elasticbeanstalk
  regoin: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-815510652541"
  bucket_path: "docker-react"
  on:
    branch: master
  acccess_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
